name: plugins_ci
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - "plugins/**"
      - "!plugins/**/*.md"
      - "!plugins/**/LICENSE"
      - "!plugins/**/.editorconfig"
      - "!plugins/**/docs/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            gcssjs-rollup:
              - 'plugins/gcssjs-rollup/**'
            gcssjs-vite:
              - 'plugins/gcssjs-vite/**'
            gcssjs-webpack:
              - 'plugins/gcssjs-webpack/**'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: |
            plugins/gcssjs-rollup/package/yarn.lock
            plugins/gcssjs-vite/package/yarn.lock
            plugins/gcssjs-webpack/package/yarn.lock

      - name: Build and publish gcssjs-rollup
        if: steps.filter.outputs.gcssjs-rollup == 'true'
        working-directory: plugins/gcssjs-rollup/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public

      - name: Build and publish gcssjs-vite
        if: steps.filter.outputs.gcssjs-vite == 'true'
        working-directory: plugins/gcssjs-vite/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public

      - name: Build and publish gcssjs-webpack
        if: steps.filter.outputs.gcssjs-webpack == 'true'
        working-directory: plugins/gcssjs-webpack/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public
