name: plugins_ci
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - "plugins/**"
      - "!plugins/**/*.md"
      - "!plugins/**/LICENSE"
      - "!plugins/**/.editorconfig"
      - "!plugins/**/docs/**"
  workflow_dispatch: null

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            grimoire-css-js-rollup:
              - 'plugins/grimoire-css-js-rollup/**'
            grimoire-css-js-vite:
              - 'plugins/grimoire-css-js-vite/**'
            grimoire-css-js-webpack:
              - 'plugins/grimoire-css-js-webpack/**'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: |
            plugins/grimoire-css-js-rollup/package/yarn.lock
            plugins/grimoire-css-js-vite/package/yarn.lock
            plugins/grimoire-css-js-webpack/package/yarn.lock

      - name: Build and publish grimoire-css-js-rollup
        if: steps.filter.outputs.grimoire-css-js-rollup == 'true'
        working-directory: plugins/grimoire-css-js-rollup/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public

      - name: Build and publish grimoire-css-js-vite
        if: steps.filter.outputs.grimoire-css-js-vite == 'true'
        working-directory: plugins/grimoire-css-js-vite/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public

      - name: Build and publish grimoire-css-js-webpack
        if: steps.filter.outputs.grimoire-css-js-webpack == 'true'
        working-directory: plugins/grimoire-css-js-webpack/package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
          npm publish --access public
